# DEV docker compose file
# Note: it uses on-host-build dockerfiles
# so before running compose build you need to build the solution
# using "dotnet build -c Release" command

version: "3.9"

services:
  auth:
    image: "germonenko.by/auth"
    container_name: "germonenko.by_auth"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.Authorization.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "5005:80"
  contacts:
    image: "germonenko.by/contacts"
    container_name: "germonenko.by_contacts"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.Contacts.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "6006:443"
  gateway:
    image: "germonenko.by/gateway"
    container_name: "germonenko.by_gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.Gateway.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "4000:80"
  products:
    image: "germonenko.by/products"
    container_name: "germonenko.by_products"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.Products.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "5002:80"
  sessions:
    image: "germonenko.by/sessions"
    container_name: "germonenko.by_sessions"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.Sessions.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "5003:80"
  users:
    image: "germonenko.by/users"
    container_name: "germonenko.by_users"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.Users.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "5001:80"
  user-termination:
    image: "germonenko.by/user-termination"
    container_name: "germonenko.by_user-termination"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      APP_CONFIG_CONNECTION_STRING: ${APP_CONFIG_CONNECTION_STRING}
    build:
      context: "./src/GermonenkoBy.UserTermination.Api"
      dockerfile: "host-build.Dockerfile"
    ports:
      - "5004:80"
  web-server:
    image: "nginx:alpine"
    container_name: "germonenko.by_web-server"
    depends_on:
      - gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local_docker:/etc/nginx/conf.d
